### PR TITLE
Add Jenkins plugins 'heavy-job' and 'jaxb'

### PR DESCRIPTION
**Pull request by cottsay**
I'm not sure how to test this change.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
> I'm not sure how to test this change.

Usually I create a test deployment branch, spin up a test farm and then do a deployment with it to verify. Did you add these by hand or use the jenkins_plugins.py script to fetch them?

**Comment by cottsay** [comment]
> ... spin up a test farm and then do a deployment with it to verify.

Alright, I just got done. There are other Jenkins-related deployment problems right now, but the plugins deployed correctly after I worked around the unrelated issues. The Jenkins management page reports no plugin conflicts, and the heavy job plugin reports as installed.

> Did you add these by hand or use the jenkins_plugins.py script to fetch them?

I added these by hand.

**Comment by cottsay** [comment]
The "other Jenkins-related deployment problems" should be resolved by ros-infrastructure/buildfarm_deployment#243 and associated PRs.

**Comment by nuclearsandwich** [comment]
Since this plugin will touch job configurations I think a post to the Buildfarm list on discourse sharing that this plugin and a corresponding ros_buildfarm commit / version will work together to bring this feature. Since Jenkins master auto-updating generally doesn't work I don't think this will break anyone but a mismatch between plugin availability and ros_buildfarm template will cause slow reconfigure jobs until reconciliation.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/jenkins-heavy-job-plugin/16265/1

**Pull request merged**
