### PR TITLE
fixing priority sorter configuration

### LINKED ISSUE #88: priority sorter plugin does not fully configure when first deployed
In the main config I had to enable 99 levels and set the default to 99. 

(It was 5 and 3 and jobs were not being prioritized.) 

And the http://54.183.26.131:8080/advanced-build-queue/ settings need to be updated too. 
There needs to be a default group giving default priority. 

And add a policy to take the priority from the job. 

I've fixed it on the farm, but the tempaltes need to be updated with these changes.

### PR DESCRIPTION
**Pull request by tfoote**
There are two files with very similar names.

Fixes #88

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The diff looks very weird. Did you first rename the file and then recreate a new file with the old name? Since the old file didn't change can you please update the commit accordingly?

**Comment by tfoote** [comment]
This is what the commit looked like from my history. I'm not sure if this is just a poor rendering by github?

```
tfoote@yeti:~/work/dbf/buildfarm_deployment Last: [0] (34s Seconds)
$ git status
On branch priority_sorter_fix
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	renamed:    master/jenkins_files/files/var/lib/jenkins/jenkins.advancedqueue.PrioritySorterConfiguration.xml -> master/jenkins_files/files/var/lib/jenkins/jenkins.advancedqueue.PriorityConfiguration.xml
	modified:   master/jenkins_files/files/var/lib/jenkins/jenkins.advancedqueue.PrioritySorterConfiguration.xml
	modified:   master/manifests/site.pp

tfoote@yeti:~/work/dbf/buildfarm_deployment Last: [0] (0s Seconds)
$ git commit -m"fixing priority sorter configuration
> There are two files with very similar names."
[priority_sorter_fix 48e3536] fixing priority sorter configuration There are two files with very similar names.
 3 files changed, 24 insertions(+), 23 deletions(-)
 rename master/jenkins_files/files/var/lib/jenkins/{jenkins.advancedqueue.PrioritySorterConfiguration.xml => jenkins.advancedqueue.PriorityConfiguration.xml} (91%)
 rewrite master/jenkins_files/files/var/lib/jenkins/jenkins.advancedqueue.PrioritySorterConfiguration.xml (95%)
```

git detected the rename vs me explicitly calling it out. I'll try to redo it more explicitly

**Comment by dirk-thomas** [comment]
You should do this in two commits. First the rename, second add the new file.

Also both xml files are currently invalid since they lack the closing tag of the root node.

**Comment by tfoote** [comment]
Even as two commits it renders the same way: https://github.com/ros-infrastructure/buildfarm_deployment/compare/priority_rebase?expand=1

**Pull request closed without merging**
