### PR TITLE
All jobs should be run with --rm now which makes this not necessary.

### PR DESCRIPTION
**Pull request by tfoote**
Fixes https://github.com/ros-infrastructure/ros_buildfarm/issues/120

### CODE REVIEW

**Comment by tfoote** [comment]
@dirk-thomas please review

**Comment by dirk-thomas** [comment]
If after numerous builds no containers accumulate on the host machine it looks good to me.

**Comment by tfoote** [comment]
We still leak the occasional container. Introspecting one of our active slaves there are well over 100 leaked in the last 48 hours.  https://gist.github.com/tfoote/ba1e8d608e98df9f1af7

I think it's worth leaving this cleanup. We just have to be sure that the minimum cleanup age is longer than any timeouts. I haven't seen any failures recently since we added the minimum age.

**Comment by dirk-thomas** [comment]
While fixing the symptom with the cleanup script might work currently I think we should investigate why these containers remain i the first place and try to fix the source of the problem.

**Comment by tfoote** [comment]
This is removing the cleanup script which is dealing with a synptom. @esteve is looking into the underlying issue. I'm going to close this removal of the cleanup, as this symptom is important to clean up in case it happens again as it can be catastrophic. (aka slaves run out of disk space)

**Comment by dirk-thomas** [comment]
If we do fix the actual problem I would recommend to merge this. Even if the result would be "catastrophic" otherwise any problem in the future in this area would go unnoticed. I think a hard failure is better then hiding a problem.

**Comment by tfoote** [comment]
I'm not sure I completely agree, but we can do that. reopened

**Comment by tfoote** [comment]
Merging this to let container leakage be apparent and the hoped fix resolve it: https://github.com/ros-infrastructure/ros_buildfarm/pull/124

**Pull request merged**
