### PR TITLE
Add workflow-cps-global-lib to plugins.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
A dependency of this plugin is needed for
https://github.com/ros-infrastructure/ros_buildfarm/pull/541

I'm not thrilled with the notion of pulling in a middleweight plugin we
don't actually use. I'd like to see us contact the maintainer of the
plugin which is causing the failure and get them to declare necessary
dependencies.

@gavanderhoorn from what I understand the error is due to the `@grab` annotation. What provides that annotation for Jenkins scripts and should it depend on ivy?

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@nuclearsandwich wrote:
> I'd like to see us contact the maintainer of the plugin which is causing the failure and get them to declare necessary dependencies.

It's not really about dependencies. I believe the posts I linked to in https://github.com/ros-infrastructure/ros_buildfarm/pull/541#issuecomment-388888562 clarify the situation.

> @gavanderhoorn from what I understand the error is due to the `@Grab` annotation. What provides that annotation for Jenkins scripts and should it depend on ivy?

It's `ivy` itself that implements all of that. The `job-dsl` Google group posting ([this one](https://groups.google.com/forum/#!msg/job-dsl-plugin/EG6eqQYYI7M/2TKKysNw4QEJ)) should explain what is going on.

**Comment by gavanderhoorn** [comment]
Btw, I've looked for an alternative implementation of the yaml serialisation code in ros-infrastructure/ros_buildfarm#541, but afaict, there is no 'native' yaml capability in Groovy that can actually write to files.

There is `readYaml` and `writeYaml`, but that comes from a plugin as well (PipeLine utility steps, or something like that).

**Comment by gavanderhoorn** [comment]
Btw: an alternative would be to just drop the `ivy` jar in the right location on the master (https://github.com/ros-infrastructure/ros_buildfarm/pull/541#issuecomment-388900584). That would remove the need for the `@Grab`.

**Comment by nuclearsandwich** [comment]
I'm still not thrilled with this as a solution, but it's been a persistent issue in test build farms and I've incorporated this plugin back into #207. I'm merging this PR so that the pre-jep-200 branch will also have this fix.

**Pull request merged**
